### ISSUE TITLE
Panics with `byte index is not a char boundary`

### ISSUE THREAD

**Issue by sdroege** [Wilfred/difftastic#146]
Diff in question is commit 1368edc014af596575278afc26b05f05675a7fe4 in https://salsa.debian.org/gstreamer-team/gst-plugins-bad1.0:

```diff
diff --git a/debian/changelog b/debian/changelog
index 91df77e..93bf977 100644
--- a/debian/changelog
+++ b/debian/changelog
@@ -1,3 +1,13 @@
+gstreamer-editing-services1.0 (1.20.0-2) unstable; urgency=medium
+
+  [ Laurent Bigonville ]
+  * Make libges-1.0-dev package depend on the proper version of
+    libpython-dev (Closes: #1005594).
+  * Also make libges-1.0-dev depend against libxml2-dev. This is listed in the
+    Requires.private dependencies of the pkg-config file.
+
+ -- Sebastian Dröge <slomo@debian.org>  Mon, 28 Feb 2022 12:40:20 +0200
+
 gstreamer-editing-services1.0 (1.20.0-1) unstable; urgency=medium
 
   * New upstream release.
```

Output:

```
thread 'main' panicked at 'byte index 349 is not a char boundary; it is inside 'ö' (bytes 348..350) of `gstreamer-editing-services1.0 (1.20.0-2) unstable; urgency=medium

  [ Laurent Bigonville ]
  * Make libges-1.0-dev package depend on the proper version of
    libpython-dev (Closes: #1005594).
  * Also make libges-1.0-dev depend against libxml2-dev. This `[...]', /home/slomo/.cargo/registry/src/github.com-1ecc6299db9ec823/difftastic-0.20.0/src/syntax.rs:588:23
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::str::slice_error_fail
   3: difft::syntax::split_words
   4: difft::line_parser::change_positions
   5: difft::diff_file
   6: difft::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal: external diff died, stopping at debian/changelog
```

**Comment by sdroege** [comment]
Sounds very likely. I'll re-open if that doesn't fix it, thanks :)

**Comment by Wilfred** [comment]
I've just released 0.21 so this fix is released. Feel free to reopen if it still reproduces.

**Comment by sdroege** [comment]
Works fine now, thanks again

**Comment by bartekbrak** [comment]
The issue still occurs when a unicode letter is part of "the context" rather than the difference. To reproduce:

```
mkdir some_repo; cd some_repo
git init
echo 'ć' >> README.md; git add README.md; git ci . -mwhatever
# first time, no problem, diff shows the letter in the diff
RUST_BACKTRACE=1 GIT_EXTERNAL_DIFF=/home/esm/.cargo/bin/difft git log -p --ext-diff
# commit again, this time, the letter will be used as context
echo 'ć' >> README.md; git add README.md; git ci . -mwhatever
# boom
RUST_BACKTRACE=1 GIT_EXTERNAL_DIFF=/home/esm/.cargo/bin/difft git log -p --ext-diff
```
 traceback:
```
thread 'main' panicked at 'byte index 1 is not a char boundary; it is inside 'ć' (bytes 0..2) of `ć`', /home/esm/.cargo/registry/src/github.com-1ecc6299db9ec823/difftastic-0.24.0/src/style.rs:48:6
stack backtrace:
   0: rust_begin_unwind
             at /build/rustc-6496Ax/rustc-1.57.0+dfsg1+llvm/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /build/rustc-6496Ax/rustc-1.57.0+dfsg1+llvm/library/core/src/panicking.rs:100:14
   2: core::str::slice_error_fail
   3: difft::style::apply_colors
   4: difft::side_by_side::print
   5: difft::print_diff_result
   6: difft::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal: external diff died, stopping at README.md
```
versions:
```
$ difft --version; rustc --version
Difftastic 0.24.0
rustc 1.57.0
```

I hope you don't mind me reopening, the problem seems similar enough.
