### ISSUE TITLE
Panic with beancount (plain text accounting) diff

### ISSUE THREAD

**Issue by davidkuridza** [Wilfred/difftastic#771]
I am using difftastic as an external git diff and it works great. It is acting up a bit lately with the changes in the [beancount](https://beancount.github.io/) format.

The minium reproducible example is:

```diff
$ git diff --no-ext-diff
diff --git a/ledger.beancount b/ledger.beancount
index d5edceb..b448f91 100644
--- a/ledger.beancount
+++ b/ledger.beancount
@@ -165,3 +165,5 @@ option "title" "My Personal Ledger"
+
+2024-10-09 * "Mercator"

$ git diff
thread 'main' panicked at /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/index.crates.io-6f17d22bba15001f/line-numbers-0.3.0/src/lib.rs:105:13:
Offset 6215 is out of bounds for a string of length 6214
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal: external diff died, stopping at ledger.beancount

$ RUST_BACKTRACE=1 git diff
thread 'main' panicked at /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/index.crates.io-6f17d22bba15001f/line-numbers-0.3.0/src/lib.rs:105:13:
Offset 6215 is out of bounds for a string of length 6214
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: line_numbers::LinePositions::from_offset
   3: line_numbers::LinePositions::from_region
   4: difft::line_parser::change_positions
   5: difft::diff_file_content
   6: difft::diff_file
   7: difft::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal: external diff died, stopping at ledger.beancount

$ RUST_BACKTRACE=full git diff
thread 'main' panicked at /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/index.crates.io-6f17d22bba15001f/line-numbers-0.3.0/src/lib.rs:105:13:
Offset 6215 is out of bounds for a string of length 6214
stack backtrace:
   0:        0x1050d39d4 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h14dcb4794e811c9f
   1:        0x104f442dc - core::fmt::write::h49a9cf68bfb4a321
   2:        0x1050d720c - std::io::Write::write_fmt::h00e4f1b82d71ad85
   3:        0x1050bffb4 - std::panicking::default_hook::{{closure}}::hda52b8046522f561
   4:        0x1050bfbb0 - std::panicking::default_hook::h9566cb73367aef3e
   5:        0x1050c0a00 - std::panicking::rust_panic_with_hook::hfa41181adbcf532d
   6:        0x1050d441c - std::panicking::begin_panic_handler::{{closure}}::ha417e66bf9de7acf
   7:        0x1050d3c0c - std::sys::backtrace::__rust_end_short_backtrace::hc7b890f013fa9efb
   8:        0x1050c0128 - _rust_begin_unwind
   9:        0x105887ca4 - core::panicking::panic_fmt::h29609029db4d41f4
  10:        0x105005158 - line_numbers::LinePositions::from_offset::h17910db74baa413d
  11:        0x1050051a4 - line_numbers::LinePositions::from_region::h98779c9a98d8110c
  12:        0x104f91fd8 - difft::line_parser::change_positions::h9bac8ecf57e3e48b
  13:        0x104f61490 - difft::diff_file_content::h196d8b24b44a0e7f
  14:        0x104f6024c - difft::diff_file::h1863f9d1100763e1
  15:        0x104f5f62c - difft::main::h859400ca65cd5f60
  16:        0x104f59d4c - std::sys::backtrace::__rust_begin_short_backtrace::h9d819bfff6612fc3
  17:        0x104fbbbac - std::rt::lang_start::{{closure}}::h0cf805743979d329
  18:        0x1050b76b8 - std::rt::lang_start_internal::h31b5cf8a92666908
  19:        0x104f62da4 - _main
fatal: external diff died, stopping at ledger.beancount
```

Another example:

```diff
$ git diff --no-ext-diff
diff --git a/ledger.beancount b/ledger.beancount
index d5edceb..6604cb6 100644
--- a/ledger.beancount
+++ b/ledger.beancount
@@ -165,3 +165,7 @@ option "title" "My Personal Ledger"
+
+2024-10-09 * "Payee"
+  Expenses:Groceries                                     12.34 EUR
+  Assets:Bank:Revolut

$ git diff
thread 'main' panicked at /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/index.crates.io-6f17d22bba15001f/line-numbers-0.3.0/src/lib.rs:105:13:
Offset 6301 is out of bounds for a string of length 6300
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal: external diff died, stopping at ledger.beancount
```

I'm using the latest difftastic and the latest macOS on MacBook Air M1:

```shell
$ difft --version
Difftastic 0.60.0 (built with rustc 1.81.0)
```

**Comment by Wilfred** [comment]
Duplicate of #755, thanks for the report!
